import type { Metadata } from "next";
import CssBaseline from "@mui/material/CssBaseline";
import ThemeProvider from "../components/ThemeProvider";
import Header from "../components/Header";
import Box from "@mui/material/Box";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <CssBaseline />

        <body>
        <Box   display="flex" flexDirection="column" minHeight="100vh">

          <Header />
          <Box>{children}</Box>
          <Footer />
        </Box>
        </body>
      </ThemeProvider>
    </html>
  );
}
