import type { Metadata } from "next";
import CssBaseline from '@mui/material/CssBaseline'
import ThemeProvider from '../components/ThemeProvider'
import Header from '../components/Header'
import Box from '@mui/material/Box'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ThemeProvider>
      <CssBaseline />
        

        <body>
        <Header /> 
          <Box>
          {children}
          </Box>
          

        </body>

      </ThemeProvider>
    </html>
  );
}
